### ISSUE TITLE
error with connection

### ISSUE THREAD

**Issue by medonomator** [basis-company/tarantool-admin#47]
Hi all, help please. If I clone the repository and try to make a connection such an error

![error](https://user-images.githubusercontent.com/15996156/71311528-a72d1080-2430-11ea-8e8f-c95c0d3227e0.png)

if I put try this command
![command](https://user-images.githubusercontent.com/15996156/71311643-b6f92480-2431-11ea-800b-4bb520cb8d32.png)

then i get it 

![error2](https://user-images.githubusercontent.com/15996156/71311679-3555c680-2432-11ea-84a9-3a8fb06a3cd2.png)
or
![error3](https://user-images.githubusercontent.com/15996156/71311682-38e94d80-2432-11ea-8a8e-875b2cd0439e.png)

tarantool container is raised through the console goes well

**Comment by Stomator** [comment]
@medonomator Hello, is this problem still actual? Did you find a solution?

**Comment by nekufa** [comment]
reopen, please, if you need some help

**Comment by funduck** [comment]
Hi, I run Tarantool using Cartridge with config
```
myapp.router1:
    advertise_uri: "localhost:3301"
    http_port: 8081
    workdir: "./tmp/data/router1"
myapp.router2:
    advertise_uri: "localhost:3302"
    http_port: 8082
    workdir: "./tmp/data/router2"
myapp.shard1_1:                                   
    advertise_uri: "localhost:3311"               
    http_port: 8083                               
    workdir: "./tmp/data/shard1_1" 
myapp.shard1_2:                    
    advertise_uri: "localhost:3312"
    http_port: 8084
    workdir: "./tmp/data/shard1_2"
myapp.shard2_1:
    advertise_uri: "localhost:3321" 
    http_port: 8085
    workdir: "./tmp/data/shard2_1"
myapp.shard2_2:
    advertise_uri: "localhost:3322"
    http_port: 8086
    workdir: "./tmp/data/shard2_2"
```
I can connect to any instance
```
:~$ tarantoolctl connect localhost:3302
connected to localhost:3302
localhost:3302> 
```
I start UI
```
docker run -e TARANTOOL_DATABASE_QUERY=true -e TARANTOOL_CONNECTIONS=guest@localhost:3301,guest@localhost:3302,guest@localhost:3311,guest@localhost:3312,guest@localhost:3321,guest@localhost:3322 -p 8000:80 quay.io/basis-company/tarantool-admin
```
But UI cannot connect to Tarantools it always returns error
```
Failed to connect to tcp://localhost:3302: Cannot assign requested address.
```
